language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libusb-1.0-0-dev
  - cd build-ext
  - ./install-librtlsdr.sh
  - cd ..
install:
  - pip install -e .
script:
  - py.test -s
