language: python
sudo: required
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5.2"
addons:
  apt:
    packages:
      - libusb-1.0-0-dev
before_install:
  - cd tools/travis
  - ./install-librtlsdr.sh
  - cd ../..
  - export LD_LIBRARY_PATH=$HOME/.local:$LD_LIBRARY_PATH
install:
  - pip install -U pip setuptools wheel
  - pip install -U pytest pytest-xdist pytest-cov coveralls
  - sh -c "if [ '$TRAVIS_PYTHON_VERSION' = '3.5.2' ]; then pip install -r doc/requirements.txt; fi"
  - pip install -e .
script:
  - sh -c "if [ '$TRAVIS_PYTHON_VERSION' = '3.5.2' ]; then travis-sphinx build --source=doc/source --nowarn; fi"
  - py.test --cov-append --cov-config .coveragerc --cov=rtlsdr
  - py.test --cov-append --cov-config .coveragerc --cov=rtlsdr --boxed --no-overrides --pyargs tests/no_override*
after_success:
  - coveralls
  - sh -c "if [ '$TRAVIS_PYTHON_VERSION' = '3.5.2' ]; then travis-sphinx deploy; fi"
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    python: "3.5.2"
    tags: true
  user: nocarryr
  password:
    secure: elyhwRlxmrrCtSxYI+hoF5dQC+sT6FbFCn4s38t24NgNexq3P5oKEXIq3s6uYWN40LvUreKsT4wZTe3H++14X6KQ1Mene8ym27jFoNWE+8UbT49alFFSX7SpmMrPQoKE4JSUbqiFOb8af+Q2Z5Lbiskcx87z0UM/YwwiNXdSse2qGZ0LK1ZTiTGFi/TFtnQKW3+bx6tKLh6FEW2j2SS70RAqBpycBYMaij2TNfVUTeAG/dYOC883yE11eBjQua+0uG/yGWbcJWe/4gfO815el5Q7+Vv0zexy40AqJviI3cGg5gXK0fPf99q45VIEeNDiNWg3uVek+nPU27GH3OtkxfmihDmvpJP+iyKW71AZN8fQ0nRrp7k6JhSmi5NuQyem5K4BcMS9HpOPEfZb66PvYwvj8Whn3UeI/xb0C6NAC5gtO5xRneglTVH3L7WPI2v/U/Pnqfd8BsQCLW+ZbiYnwVoWm8NAxqymKhiCG7CVpBMWvoM75Hi8QRRymTYmAWfJxUFpVVlRBYwYGl+oNCA/ETsP1JmNqoRPGB1ln8EZpM2VNrNWMYKMsQw9EtZbT7XdNq1kN48nQdG01koVSd9Yui1AArsCowynd6XKoFlAO47NUVPxxeo9Q4wUQzGZBwOtsViXo4aH0RfXMT4VZYpeQ+NQVZtpAUr0OxjRdf7yxt4=
