language: python
python:
- '2.7'
- '3.4'
- '3.5'
addons:
  apt:
    packages:
    - libusb-1.0-0-dev
    - pandoc
before_install:
- cd tools/travis
- ./install-librtlsdr.sh
- cd ../..
- export LD_LIBRARY_PATH=$HOME/.local:$LD_LIBRARY_PATH
install:
- pip install -e .
script:
- py.test
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    tags: true
  #user: roger?
