language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - wget https://github.com/steve-m/librtlsdr/archive/v0.5.3.tar.gz
  - tar xvzf librtlsdr-0.5.3.tar.gz
  - cd rtl-sdr && autoreconf -i && make && sudo make install && sudo ldconfig
script:
  - py.test test.py
