name: Test pyrtlsdrlib integration

on:
  push:
    branches: [ master, rtlsdrlib-integration ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: MatteoH2O1999/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        cache-build: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -U pytest pytest-cov
        pip install numpy
    - name: Install pyrtlsdr with lib
      run: pip install -e '.[lib]'
    - name: Test with pytest
      shell: bash
      run: |
        py.test --cov-config .coveragerc --cov=rtlsdr
        py.test --cov-append --cov-config .coveragerc --cov=rtlsdr --no-overrides --pyargs tests/no_override_client_mode.py
        py.test --cov-append --cov-config .coveragerc --cov=rtlsdr --no-overrides --pyargs tests/no_override_dll_loader.py
